### PR TITLE
fix(compatibility): use a shim for Object.values

### PR DESCRIPTION
**Pull request by fczuardi**
This can be a little tricky to test, you will need to find a browser that don't support Object.values to compare the behavior before and after the patch. I will comment some directions if I find simple ways of doing that, and having some process for us to test different browsers is a discussion/enhancement that we need for farmblocks and webapp, maybe we could file an issue for that.

affects: @crave/farmblocks-link, @crave/farmblocks-text

ISSUES CLOSED: #197

### CODE REVIEW

**Comment by fczuardi** [comment]
rebased and conflicts resolved

**Comment by fczuardi** [comment]
also, browserstack invites were sent

**Comment by vNakamura** [comment]
😓 Storybook already uses a polyfill for Object.values. So we need to find another way to test it.

**Comment by fczuardi** [comment]
@vNakamura https://stackblitz.com with the README usage code of the affected components?

first with the regular version, to see the failing, then with the specific canary of this branch (need to copy paste from travis log) to see the fix?

**Comment by vNakamura** [comment]
@fczuardi Great, I could test this way!
To other reviewers, the version is: `@crave/farmblocks-input-text@0.3.0-alpha.a4bbf04a`

**Comment by vNakamura** [comment]
Coverage reduced

**Comment by fczuardi** [comment]
rebased

**Comment by fczuardi** [comment]
rebased and resolved conflicts

**Pull request merged**
