### PR TITLE
drop husky in favor of precommit

### LINKED ISSUE #43: [precommit] run prettier only on staged hunks instead of staged files
see https://github.com/CraveFood/farmblocks/pull/19#issuecomment-332618737

The related issue and discussion on the lint-staged project repo: https://github.com/okonet/lint-staged/issues/62

### PR DESCRIPTION
**Pull request by fczuardi**
closes #43 
closes: #21

changed the task name previously know as precommit to lint-staged because it might be useful to keep
it for manually fixing staging before commiting even without a hook

### CODE REVIEW

**Comment by alcferreira** [comment]
Branch has conflicts.

**Comment by fczuardi** [comment]
this branch depends on #46 so after that PR lands, we need to rebase this one

**Comment by rafayepes** [comment]
@fczuardi why didn't your remove lint-staged here? Doesn't it overlap with pre-commit?

**Comment by fczuardi** [comment]
@rafayepes no particular strong reason, and yes, they do overlap.

Maybe my subjective personal reasoning was to keep it around as a reminder that a js-only stack can be achieved someday, when linst-staged gets to parity with our requirements :(

Definitely redundant today and can be chopped off.

**Pull request merged**
