### PR TITLE
Fix fluid button text alignment

### PR DESCRIPTION
**Pull request by fgameiro**
Closes: #88

### CODE REVIEW

**Comment by fczuardi** [comment]
Ok, you need to update the snapshots with:

```
yarn test -u
```

**Comment by fgameiro** [comment]
I was talking with @alcferreira about this: the tests are running fine locally -- 100% passed. But it's broken here on something I didn't even touch (alert components storyshots). We don't know why.

**Comment by fczuardi** [comment]
I can reproduce it on my machine using ``yarn install --frozen-lockfile``

And the diff is for some classnames only, so it might be something on a dependency that changed the hash of the styled components of the alert component...

I will submit a commit and see if it fixes travis

**Comment by fczuardi** [comment]
that didnt work, my local hash is still different from travis,looks like a bug on jest snapshots

**Comment by fczuardi** [comment]
there is this project https://github.com/styled-components/jest-styled-components that can be a possible fix and makes styles changes more useful on snapshots as well, I am opening issue #106 to address that

**Comment by fczuardi** [comment]
Ok, I found the cause of the different hashes... we should run the build task ``yarn build`` to generate the es5 version of the farmblocks components before generating our snapshots, because travis does that too.

**Pull request merged**
